paths:
  uploads: "docs/assets"
  uploads_filename:
  uploads_use_relative_path:
  static: ""
  dam_uploads:
  dam_uploads_filename:
  dam_static:
  collections:
  data:
  layouts:
  includes:
collections_config:
  docs:
    path: docs
    output: true
    url: /[full_slug]/
    filter:
      base: strict
      exclude:
        - /schema
        - /schema.json
    name: Documentation
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true

timezone: Etc/UTC
