paths:
#  uploads: "docs/assets"
  uploads_filename:
  uploads_use_relative_path: true
  static: ""
  dam_uploads:
  dam_uploads_filename:
  dam_static:
  collections:
  data:
  layouts:
  includes:
#brandon changed this
  uploads: '[base_path]/assets'

collections_config:
  docs:
    path: docs
    output: true
    url: /[full_slug]/
    filter:
      base: strict
      exclude:
        - /schema
        - /schema.json
    name: Documentation
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_editables:
  content:
    allow_custom_markup: true
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
    snippet: true
_inputs:
  image:
    type: image
    options:
      paths:
        uploads: images
      accepts_mime_type:
        - image/png
        - image/jpeg
        - image/jpg
      allowed_sources:
        - site-files
      empty_type: 
      resize_style: contain
      width: 400
      height: 300
      expandable: true
#      prevent_resize_existing_files: false
#brandon changed this
      prevent_resize_existing_files: true
      mime_type: image/png
      sizes:
        - size: 2x
          target: _retina_image_file
image: /docs/assets/image.png
_retina_image_file: /docs/assets/image-2x.png
source_editor:
  tab_size: 4
content_editor:
  tab_size: 4

_snippets_imports:
  python_markdown_extensions:
    include:
      - python_markdown_admonition
      - python_markdown_collapsible_admonition


timezone: Etc/UTC
