paths:
#  uploads: "docs/assets"
  uploads_filename:
  uploads_use_relative_path: true
  static: ""
  dam_uploads:
  dam_uploads_filename:
  dam_static:
  collections:
  data:
  layouts:
  includes:
#brandon changed this
  uploads: '[base_path]/assets'

collections_config:
  docs:
    path: docs
    output: true
    url: /[full_slug]/
    filter:
      base: strict
      exclude:
        - /schema
        - /schema.json
    name: Documentation
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_editables:
  content:
    allow_custom_markup: true
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
    snippet: true
_inputs:
#brandon added this 4/29/25 to add default descriptions
  title:
    type: text           # simple single-line text field
    label: Title         # human-friendly label
    description: Enter the article title
    context:
      path: "docs/**/*.md"
  description:
    type: textarea       # multi-line text area
    label: Description   # human-friendly label
    description: A short summary of the article
    context:
      path: "docs/**/*.md"

  image:
    type: image
    options:
      paths:
        uploads: images
      accepts_mime_type:
        - image/png
        - image/jpeg
        - image/jpg
      allowed_sources:
        - site-files
      empty_type: 
      resize_style: contain
      width: 400
      height: 300
      expandable: true
#      prevent_resize_existing_files: false
#brandon changed this
      prevent_resize_existing_files: true
      mime_type: image/png
      sizes:
        - size: 2x
          target: _retina_image_file

image: /docs/assets/image.png
_retina_image_file: /docs/assets/image-2x.png
source_editor:
  tab_size: 4
content_editor:
  tab_size: 4
  
#brandon added this
_snippets_imports:
  python_markdown_extensions:
    include:
      - python_markdown_admonition
      - python_markdown_collapsible_admonition
      - python_markdown_tabs

timezone: Etc/UTC

#brandon added these for adding buttons
_snippets:
  mkdoc_button:
    snippet: "[[[button_text]]]([[button_link]]){ [[button_class]] }"
    preview:
      text:
        - key: button_text
        - 'Button'
      subtext:
        - key: button_link
      metadata:
        - text:
            - key: button_icon
    picker_preview:
      text: Button
    params:
      button_text:
        parser: content
        options:
          editor_key: button_text
          forbidden_tokens: ["]", ":"]
          style:
            trim_text: true
      button_link:
        parser: argument
        options:
          model:
            editor_key: button_link
          format:
            forbidden_tokens: [")"]
            string_boundary: ['']
      button_class:
        parser: content
        options:
          editor_key: button_class
          forbidden_tokens: ["}"]
          style:
            trim_text: true
    _inputs:
      button_class:
        type: select
        label: Button type
        options:
          values:
            - name: Primary
              class: '.md-button .md-button--primary'
            - name: Secondary
              class: '.md-button'
          value_key: class
          allow_empty: false
  mkdoc_button_with_icon:
    snippet: "[[[button_text]] :[[button_icon]]:]([[button_link]]){ [[button_class]] }"
    preview:
      text:
        - key: button_text
        - 'Button'
      subtext:
        - key: button_link
      metadata:
        - text:
            - key: button_icon
    picker_preview:
      text: Button with icon
    params:
      button_text:
        parser: content
        options:
          editor_key: button_text
          forbidden_tokens: ["]", ":"]
          style:
            trim_text: true
      button_link:
        parser: argument
        options:
          model:
            editor_key: button_link
          format:
            forbidden_tokens: [")"]
            string_boundary: ['']
      button_class:
        parser: content
        options:
          editor_key: button_class
          forbidden_tokens: ["}"]
          style:
            trim_text: true
      button_icon:
        parser: content
        options:
            editor_key: button_icon
            forbidden_tokens: [':']
    _inputs:
      button_class:
        type: select
        label: Button type
        options:
          values:
            - name: Primary
              class: '.md-button .md-button--primary'
            - name: Secondary
              class: '.md-button'
          value_key: class
          allow_empty: false
      button_icon:
        type: text
        label: Button Icon
        comment: >
          Search available icons <a href="https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search">here</a>. Remove the colons on each side when pasting.
