paths:
  uploads: "docs/assets"
  uploads_filename:
  uploads_use_relative_path: true
  static: ""
  dam_uploads:
  dam_uploads_filename:
  dam_static:
  collections:
  data:
  layouts:
  includes:
collections_config:
  docs:
    path: docs
    output: true
    url: /[full_slug]/
    filter:
      base: strict
      exclude:
        - /schema
        - /schema.json
    name: Documentation
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    
_snippets_imports:
  python_markdown_extensions:
    include:
      - python_markdown_admonition
      - python_markdown_collapsible_admonition
      - python_markdown_button
      - python_markdown_reference_button
      - python_markdown_diagram
      - python_markdown_code_block
      - python_markdown_footnote
      - python_markdown_footnote_marker
      - python_markdown_icon
      - python_markdown_inline_code
      - python_markdown_mathjax
      - python_markdown_inline_mathjax
      - python_markdown_tabs
      - python_markdown_marker
      - python_markdown_block_snippet
      - python_markdown_image
      - python_markdown_reference_image
      - python_markdown_reference_template_image
      - python_markdown_reference_link
      - python_markdown_link
      - python_markdown_reference
      - python_markdown_abbreviation
      - python_markdown_reference_template
_snippets:
  result:
    template: python_markdown_markdown_in_html
    inline: false
    preview:
      text: Result
    definitions:
      tag_name: div
      content_key: content
      tag_attributes:
        - source_key: class
          type: string
          default: result
          allowed_values:
            - result
    _inputs:
      content:
        type: markdown
_inputs:
  image:
    type: image
    options:
      paths:
        uploads: images
      accepts_mime_type:
        - image/png
        - image/jpeg
        - image/jpg
      allowed_sources:
        - site-files
      empty_type: 
      resize_style: contain
      width: 400
      height: 300
      expandable: true
      prevent_resize_existing_files: false
      mime_type: image/png
      sizes:
        - size: 2x
          target: _retina_image_file
image: /docs/assets/image.png
_retina_image_file: /docs/assets/image-2x.png
source_editor:
  tab_size: 4
content_editor:
  tab_size: 4

timezone: Etc/UTC
