extra_css:
  - stylesheets/extra.css
site_name: Apollo Docs
site_url: https://apolloautomation.github.io/
repo_url: https://github.com/ApolloAutomation/docs
edit_uri: https://github.com/ApolloAutomation/docs/edit/main/docs

use_directory_urls: true
theme:
  logo: assets/Apollo_Square.png
  favicon: assets//favicon.png
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.edit
    - content.code.copy
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: green

plugins:
  - glightbox:
      draggable: false
  - search
  - social:
      cards_layout_options:
        background_color: "#111111"
        color: "#daa520"
        font_family: Figtree

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ApolloAutomation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ApolloAutomation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mMNgQPyF94

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/ApolloAutomation"  target="_blank" rel="noopener">Apollo Automation LLC</a>

nav:
  - Home: index.md
  - General:
      - Getting Started: general/Setup/Getting-Started.md
  - Products:
      - MSR-1:
          - FAQ: sensors/msr1/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Updating: sensors/msr1/updating.md
          - Bluetooth Tracking: general/bluetoothtracking.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - MSR-2:
          - FAQ: sensors/msr2/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Updating: sensors/msr2/updating.md
          - Bluetooth Tracking: general/bluetoothtracking.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - AIR-1:
          - FAQ: sensors/air1/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Updating: sensors/air1/updating.md
          - Bluetooth Tracking: general/bluetoothtracking.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - MTR-1:
          - FAQ: sensors/mtr1/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Updating: sensors/mtr1/updating.md
          - Bluetooth Tracking: general/bluetoothtracking.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - PLT-1:
          - FAQ: sensors/plt1/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Updating: sensors/plt1/updating.md
          - Bluetooth Tracking: general/bluetoothtracking.md
          - Reviews: example.md
          - Examples: example.md
      - ODroid Hub:
          - FAQ: sensors/odroidhub/faq.md
          - Getting Started: general/Setup/Getting-Started.md
          - Reviews: example.md
  - DIY: example.md
  - Contact Us: contact.md
    