extra_css:
  - stylesheets/extra.css
  - https://unicons.iconscout.com/release/v4.0.8/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  # - css/lightgallery.min.css
  - stylesheets/extra.css
  - stylesheets/nocopy.css
  - stylesheets/design.css
  - stylesheets/osano.css
  - stylesheets/pmm.css
site_name: Apollo Docs
site_url: https://apolloautomation.github.io/
repo_url: https://github.com/ApolloAutomation/docs
edit_uri: https://github.com/ApolloAutomation/docs/edit/main/docs
site_author: Apollo Automation LLC

use_directory_urls: true
theme:
  logo: assets/Apollo_Square.png
  favicon: assets/favicon.png
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.edit
    - content.code.copy
    - content.code.annotate
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Color theme set to Automatic. Click to change
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Color theme set to Light Mode. Click to change
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Color theme set to Dark Mode. Click to change

plugins:
  - glightbox:
      draggable: false
  - search
  - social:
      cards_layout_options:
        background_color: "#111111"
        color: "#daa520"
        font_family: Figtree

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ApolloAutomation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ApolloAutomation
    - icon: fontawesome/brands/discord
      link: https://dsc.gg/apolloautomation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "docs"
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - extra
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#brandon added this 1/8/25
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

#brandon added this 1/10/25
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/ApolloAutomation"  target="_blank" rel="noopener">Apollo Automation LLC</a>

nav:
  - Apollo: 
      - General:
          - Home: index.md
          - Introduction: products/general/introduction.md
          - FAQ: products/general/faq.md
          - Getting Started: products/general/setup/getting-started.md
          - Additional Info:
            - Calibrating:
              - CO<sub>2</sub>: products/general/calibrating-and-updating/co2-calibration.md
              - CO<sub>2</sub> Quick: products/general/calibrating-and-updating/co2-calibration-quick.md
              - Temperature and Humidity: products/general/temp-hum-calibration.md
              - Radar Tuning:
                - Home Assistant: products/msr1/calibrating-and-updating/zones-ha.md
                - HLK Radar Tool App: products/msr1/calibrating-and-updating/zones-hlk.md
                - mmWave Tuning Videos: products/general/calibrating-and-updating/mmwave-videos.md
              - Zone Configuration:
                - Home Assistant: products/mtr1/setup/zones-ha.md
                - HLK Radar Tool App: products/mtr1/setup/zones-hlk.md
            - Updating: products/general/calibrating-and-updating/updating-firmware.md
            - Renaming Devices: products/general/setup/renaming-apollo-devices.md
            - Change Update Frequency: products/general/setup/change-the-update-frequency-of-sensors.md
            - Adding SCD40 Temp/Hum: products/general/setup/how-to-add-temp-and-humidity-from-scd40.md
            - Adjusting WiFi Power: products/general/setup/adjusting-wifi-power.md
            - Hidden WiFi Networks: products/general/setup/adding-apollo-devices-to-hidden-networks.md
            - Bluetooth Proxy: products/general/setup/bluetooth-proxy.md
            - Bluetooth Tracking: products/general/setup/bluetooth-tracking.md
            - Piezo Buzzer: products/general/piezo.md
            - Switch to Beta: products/general/setup/switch-to-beta-branch.md
          - Troubleshooting:
            - Uploading Code Through ESPHome: products/general/troubleshooting/manually-uploading-code-through-esphome.md
            - Removing Devices: products/general/troubleshooting/removing-device-from-home-assistant.md
            - Connection Issues: products/general/troubleshooting/connection-issues.md
            - Unifi Auto Discover Device mDNS Issue: products/general/troubleshooting/ubiquiti-unifi-mdns-auto-discover-issue.md
            - OPNsense Auto Discover Device mDNS Issue: products/general/troubleshooting/opnsense-mdns-auto-discover-issue.md
          - Battery Sensors:
            - How To Wake Up Your Sensor: products/general/battery-sensors/wake-up-battery-sensor.md
            - Keep Your Sensor Awake With HA Helper: products/general/battery-sensors/awake-ha-helper.md
            - Sensor Connection Check: products/general/battery-sensors/sensor-connection-check.md
          - Source Code and 3D Files: products/general/links.md
          - Sensor Comparisons: products/general/comparisons.md
      - MSR-1:
          - Introduction: products/msr1/introduction.md
          - FAQ: products/msr1/faq.md
          - Getting Started: products/general/setup/getting-started-msr1.md
          - Additional Info:
            - General Tips: products/msr1/setup/general-tips.md
            - Sensor Definitons: products/msr1/setup/sensor-definitions.md
            - Radar Tuning: 
              - Home Assistant: products/msr1/calibrating-and-updating/zones-ha.md
              - HLK Radar Tool App: products/msr1/calibrating-and-updating/zones-hlk.md
              - mmWave Tuning Videos: products/general/calibrating-and-updating/mmwave-videos.md
            - Exposed GPIO: products/msr1/additional-info/exposed-gpio.md
          - Addons: products/msr1/addons/adding-co2-to-msr-1.md
          - Reviews: products/msr1/msr1-reviews.md
          - Examples:
            - MSR-1 Dashboards: products/msr1/examples/msr1-dashboards.md
            - MSR-1 Alarmo: products/msr1/examples/msr1-alarmo.md
          - Troubleshooting:
            - MSR-1 Boot Mode: products/msr1/troubleshooting/msr1-boot-mode.md
            - Manually Uploading Code To MSR-1: products/msr1/troubleshooting/msr1-code.md
            - Teardown and Reassembly Of MSR-1: products/msr1/troubleshooting/msr1-teardown.md
            - Reset Wi-Fi Credentials: products/msr1/troubleshooting/msr1-reset-wi-fi-credentials.md
      - MSR-2:
          - Introduction: products/msr2/introduction.md
          - FAQ: products/msr2/faq.md
          - Getting Started: products/general/setup/getting-started-msr2.md
          - Additional Info:
            - General Tips: products/msr2/setup/msr2-general-tips.md
            - Sensor Definitons: products/msr2/setup/msr2-sensor-definitions.md
            - Radar Tuning:
              - Home Assistant: products/msr2/calibrating-and-updating/zones-ha.md
              - HLK Radar Tool App: products/msr2/calibrating-and-updating/zones-hlk.md
              - mmWave Tuning Videos: products/general/calibrating-and-updating/mmwave-videos.md
          - Addons: products/msr2/addons/adding-co2-to-msr-2.md
          - Reviews: products/msr2/msr2-reviews.md
          - Examples:
            - MSR-2 Dashboards: products/msr2/examples/msr2-dashboards.md
            - MSR-2 Alarmo: products/msr2/examples/msr2-alarmo.md
          - Troubleshooting:
            - MSR-2 Boot Mode: products/msr2/troubleshooting/msr2-boot-mode.md
            - Manually Uploading Code To MSR-2: products/msr2/troubleshooting/msr2-code.md
            - Teardown and Reassembly Of MSR-2: products/msr2/troubleshooting/msr2-teardown.md
            - Reset Wi-Fi Credentials: products/msr2/troubleshooting/msr2-reset-wi-fi-credentials.md
      - MTR-1:
          - Introduction: products/mtr1/introduction.md
          - FAQ: products/mtr1/faq.md
          - Getting Started: products/general/setup/getting-started-mtr1.md
          - Additional Info:
            - General Tips: products/mtr1/setup/general-tips.md
            - Sensor Definitons: products/mtr1/setup/sensor-definitions.md
            - Zone Configuration:
              - Home Assistant: products/mtr1/setup/zones-ha.md
              - HLK Radar Tool App: products/mtr1/setup/zones-hlk.md
          - Addons: products/mtr1/addons/adding-co2-to-mtr-1.md
          - Reviews: products/mtr1/mtr1-reviews.md
          - Examples:
            - MTR-1 Corner Mount: products/mtr1/examples/crookedtoe-mtr1.md
            - MTR-1 Alarmo: products/mtr1/examples/mtr1-alarmo.md
          - Troubleshooting:
            - MTR-1 Boot Mode: products/mtr1/troubleshooting/mtr1-boot-mode.md
            - Manually Uploading Code To MTR-1: products/mtr1/troubleshooting/mtr1-code.md
            - Teardown and Reassembly Of MTR-1: products/mtr1/troubleshooting/mtr1-teardown.md
            - Reset Wi-Fi Credentials: products/mtr1/troubleshooting/mtr1-reset-wi-fi-credentials.md
      - AIR-1:
          - Introduction: products/air1/introduction.md
          - FAQ: products/air1/faq.md
          - Getting Started: products/general/setup/getting-started-air1.md
          - Additional Info:
            - General Tips: products/air1/setup/general-tips.md
            - Sensor Definitons: products/air1/setup/sensor-definitions.md
          - Addons:
            - CO<sub>2</sub> Addon: products/air1/addons/adding-co2-to-air-1.md
            - MiCS Addon: products/air1/addons/adding-the-mics-4514-gas-sensor-to-the-air-1.md
            - GPIO Addon: products/air1/addons/adding-gpio-header-to-air-1.md
          - Reviews: products/air1/air1-reviews.md
          - Examples:
            - Air Quality Dashboard: products/air1/examples/air1-dashboard-examples.md
            - Firstof9's Apex Charts: products/air1/examples/firstof9's-apex-charts.md
            - GPIO Header LED Strip: products/air1/examples/how-to-use-the-apollo-gpio-header-to-control-an-led-strip.md
          - Troubleshooting:
            - AIR-1 Boot Mode: products/air1/troubleshooting/air1-boot-mode.md
            - Manually Uploading Code To AIR-1: products/air1/troubleshooting/air1-code.md
            - Teardown and Reassembly Of AIR-1: products/air1/troubleshooting/air1-teardown.md
            - Reset Wi-Fi Credentials: products/air1/troubleshooting/air1-reset-wi-fi-credentials.md
      - PLT-1:
          - Introduction: products/plt1/introduction.md
          - FAQ: products/plt1/faq.md
          - Getting Started: products/general/setup/getting-started-plt1.md
          - Additional Info:
            - General Tips: products/plt1/general-tips.md
            - Sensor Definitons: products/plt1/sensor-definitions.md
            - Calibrating Soil Moisture: products/plt1/calibrating-plt1.md
          - Reviews: products/plt1/reviews.md
          - Examples: 
            - Flower Card: products/plt1/examples/flower-card.md
          - Troubleshooting:
            - PLT-1 Boot Mode: products/plt1/plt1-boot-mode.md
            - Manually Uploading Code To PLT-1: products/plt1/plt1-code.md
            - Teardown and Reassembly Of PLT-1: products/plt1/plt1-teardown.md
      - PLT-1B:
          - Introduction: products/plt1b/introduction.md
          - FAQ: products/plt1b/faq.md
          - Getting Started: products/general/setup/getting-started-plt1.md
          - Additional Info:
            - General Tips: products/plt1b/general-tips.md
            - Sensor Definitons: products/plt1/sensor-definitions.md
            - Calibrating Soil Moisture: products/plt1/calibrating-plt1.md
            - How To Wake Up Your Sensor: products/general/battery-sensors/wake-up-battery-sensor.md
            - Keep Your Sensor Awake With HA Helper: products/general/battery-sensors/awake-ha-helper.md
            - Sensor Connection Check: products/general/battery-sensors/sensor-connection-check.md
          - Reviews: products/plt1/reviews.md
          - Examples: 
            - Flower Card: products/plt1/examples/flower-card.md
          - Troubleshooting:
            - PLT-1 Boot Mode: products/plt1b/plt1b-boot-mode.md
            - Manually Uploading Code To PLT-1: products/plt1b/plt1b-code.md
            - Teardown and Reassembly Of PLT-1: products/plt1b/plt1b-teardown.md
      - H-1:
          - Introduction: products/h1/introduction.md
          - FAQ: products/h1/faq.md
          - Getting Started: products/h1/getting-started.md
          - Reviews: products/h1/reviews.md
          - Examples: 
            - Holiday Songs: products/h1/holiday-songs.md
          - Troubleshooting:
            - H-1 Boot Mode: products/h1/boot-mode.md
            - Manually Uploading Code To H-1: products/h1/code.md
      - Apollo ODroid:
          - Introduction: products/apolloodroid/introduction.md
          - FAQ: products/apolloodroid/faq.md
          - Getting Started: products/apolloodroid/getting-started.md
          - Reviews: products/apolloodroid/reviews.md
      - DEV-1:
          - Introduction: products/dev1/introduction.md
      - Contact Us / Support: products/general/contact-us/contact-us-support.md
    
    