extra_css:
  - stylesheets/extra.css
  - https://unicons.iconscout.com/release/v4.0.8/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css
  # - css/lightgallery.min.css
  - stylesheets/extra.css
  - stylesheets/nocopy.css
  - stylesheets/design.css
  - stylesheets/osano.css
  - stylesheets/pmm.css
site_name: Apollo Docs
site_url: https://apolloautomation.github.io/
repo_url: https://github.com/ApolloAutomation/docs
edit_uri: https://github.com/ApolloAutomation/docs/edit/main/docs
site_author: Apollo Automation LLC

use_directory_urls: true
theme:
  logo: assets/Apollo_Square.png
  favicon: assets//favicon.png
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.edit
    - content.code.copy
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Color theme set to Automatic. Click to change
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Color theme set to Light Mode. Click to change
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Color theme set to Dark Mode. Click to change

plugins:
  - glightbox:
      draggable: false
  - search
  - social:
      cards_layout_options:
        background_color: "#111111"
        color: "#daa520"
        font_family: Figtree

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ApolloAutomation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ApolloAutomation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mMNgQPyF94

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/ApolloAutomation"  target="_blank" rel="noopener">Apollo Automation LLC</a>

nav:
  - Home: index.md
  - Products:
      - General:
          - Introduction: products/general/introduction.md
          - Getting Started: products/general/setup/getting-started.md
      - MSR-1:
          - Introduction: products/msr1/introduction.md
          - FAQ: products/msr1/faq.md
          - Getting Started: products/msr1/gettingstarted.md
          - Additional Info:
            - Updating: products/msr1/updating.md
            - Calibrating:
                - Calibrating CO2: products/msr1/calibrating/co2.md
            - Bluetooth Proxy: products/msr1/bluetoothproxy.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - MSR-2:
          - Introduction: products/msr2/introduction.md
          - FAQ: products/msr2/faq.md
          - Getting Started: products/msr2/gettingstarted.md
          - Additional Info:
            - Updating: products/msr2/updating.md
            - Calibrating:
                - Calibrating CO2: products/msr2/calibrating/co2.md
            - Bluetooth Tracking: products/msr2/bluetoothproxy.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - AIR-1:
          - Introduction: products/air1/introduction.md
          - FAQ: products/air1/faq.md
          - Getting Started: products/air1/gettingstarted.md
          - Additional Info:
            - Updating: products/air1/updating.md
            - Calibrating:
                - Calibrating CO2: products/air1/calibrating/co2.md
            - Bluetooth Tracking: products/air1/bluetoothproxy.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - MTR-1:
          - Introduction: products/mtr1/introduction.md
          - FAQ: products/mtr1/faq.md
          - Getting Started: products/mtr1/gettingstarted.md
          - Additional Info:
            - Updating: products/mtr1/updating.md
            - Calibrating:
                - Calibrating CO2: products/mtr1/calibrating/co2.md
            - Bluetooth Tracking: products/mtr1/bluetoothproxy.md
          - Reviews: example.md
          - Examples: example.md
          - Troubleshooting: example.md
      - PLT-1:
          - Introduction: products/plt1/introduction.md
          - FAQ: products/plt1/faq.md
          - Getting Started: products/plt1/gettingstarted.md
          - Additional Info:
            - Updating: products/plt1/updating.md
            - Bluetooth Tracking: products/plt1/bluetoothproxy.md
            - Sensor Definitons: products/plt1/sensor-definitions.md
          - Reviews: products/plt1/reviews.md
          - Examples: 
            - Flower Card: products/plt1/examples/flower-card.md
          - Troubleshooting: products/plt1/troubleshooting.md
      - Apollo ODroid:
          - Introduction: products/apolloodroid/introduction.md
          - FAQ: products/apolloodroid/faq.md
          - Getting Started: products/apolloodroid/setup/getting-started.md
          - Reviews: example.md
  - DIY: example.md
  - Contact Us: contact.md
    