extra_css:
  - stylesheets/extra.css
site_name: Apollo Docs
site_url: https://wiki.apolloautomation.com
theme:
  logo: assets/Apollo_Square.png
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: green

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ApolloAutomation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ApolloAutomation
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mMNgQPyF94

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/ApolloAutomation"  target="_blank" rel="noopener">Apollo Automation LLC</a>

nav:
  - Home:
    - Sensors:
      - Getting Started: sensors/gettingstarted.md
      - Bluetooth Tracking: sensors/bluetoothtracking.md
      - MSR-1:
        - Updating: sensors/msr1/updating.md
    - Contact Us: contact.md