name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-material[imaging]
      - run: sudo apt-get install imagemagick pngquant
      - run: find . -name '*.png' -execdir bash -c 'mogrify -resize '750x>' "$1"' - {} \;
      - run: find . -name '*.png' -execdir bash -c 'pngquant "$1" --ext .png --force' - {} \;
      # Replace 2 spaces with 4 spaces in list items
      - name: Replace two spaces with four before list items
        run: |
          find . -name '*.md' -exec sed -i 's/^  \*/    */' {} \;
      - run: mkdocs gh-deploy --force
 
  notify:
    name: Notify on Failure
    needs: [ deploy ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.deploy.result }}
          title: Build Failed - Docs
          description: Docs deploy job failed. Check the logs for details.
          content: "Hey <@&1355984268496605356>"